spring:
  application:
    name: deliveryman

  datasource:
    url: jdbc:postgresql://localhost:5432/deliveryman
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

jwt:
  secret-key: GZiuJYlBH9G6i+sE4g9UzlgkNjp8BrdS7BxqElNh8lGDGTG1JWkou0jtSr9ZygvL
  expirationTime: 86400000